version: "3"
services:
  speculos:
    image: ghcr.io/ledgerhq/speculos
    container_name: speculos
    command: --display headless apps/app.elf --sdk 1.6 --seed "secret"
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - ./bin:/speculos/apps
