version: "3"
services:
  speculos:
    image: ghcr.io/ledgerhq/speculos
    container_name: speculos
    command: --display headless apps/app.elf --sdk 1.6 --seed "secret" --model nanos
    restart: unless-stopped
    ports:
      - '5001:5001'
    volumes:
      - ./bin:/speculos/apps
